# Generated by Django 4.2 on 2023-04-09 13:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image_postview_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post_image.jpg', upload_to=blog.models.user_directory_path),
        ),
    ]
